### ISSUE TITLE
Current version isn't updating from CI pipeline

### ISSUE THREAD

**Issue by scottfrederick** [cloudfoundry-community/traveling-cf-admin#11]
@drnic The [`version`](https://github.com/cloudfoundry-community/traveling-cf-admin/blob/master/cf-cli-release/version) and [`tag`](https://github.com/cloudfoundry-community/traveling-cf-admin/blob/master/cf-cli-release/tag) files haven't been updated since `6.14.1`. Maybe because of build failures starting around [build 15](http://ci.starkandwayne.com:8080/pipelines/traveling-cf-admin/jobs/job-traveling-cf-admin/builds/15)? 

Manually changing those files might get things in sync again. Or is there a better way to fix this?

**Comment by william-tran** [comment]
I needed to do a few things in my fork to locally build a working release. I already had rbenv installed and the cf and uaac paths were not using travelling-cf-admin's so I tried to uninstall those so the only ones that existed on that environment were the ones pulled in by the project. Maybe that wasn't entirely necessary but it did allow me to verify the release.
1. `rbenv local 2.1.0`
2. Do this commit https://github.com/william-tran/traveling-cf-admin/commit/352799c633af9e0a6a37985eeea87be7ebaedc43
3. update repo paths to my fork https://github.com/william-tran/traveling-cf-admin/commit/fa2ddb39696965269e18ba134d46c5363838db8c
4. gem install bundler
5. bundle install
6. `rake package` this would error out strangely
   
   ```
   tar xzf packaging/cf-6.16.1-linux-x86.tgz -C cf-admin-6.16.1-linux-x86
   cf: (Empty error message)
   tar: Error exit delayed from previous errors.
   rake aborted!
   Command failed with status (1): [tar xzf packaging/cf-6.16.1-linux-x86.tgz ...]
   ```
7. `rake package` again
8. Create a github token and `export GITHUB_TOKEN=abc123`
9. `brew install go; export GOPATH=$HOME; go get github.com/aktau/github-release`
10. `rake release`
