### ISSUE TITLE
uaac options parser doesn't deal with spaces in option values

### ISSUE THREAD

**Issue by william-tran** [cloudfoundry-community/traveling-cf-admin#7]
My regular uaac 3.1.0 (not from this package) allows for uaac curl commands with spaces in the options, eg the space after the colon in Content-type:

```
uaac curl /oauth/clients -k -H "Content-type: application/json"
```

Running the same command from this package outputs

```
Too many command line parameters given.

  curl [path]                      CURL to a UAA endpoint
                                   -X | --request <method>, request method type, defaults to GET
                                   -d | --data <data>, data included in request body
                                   -H | --header <header>, header to be included in the request
                                   -k | --insecure, makes request without verifying SSL certificates
```

This is a problem when specifying -d request body data that may need to contain spaces.

**Comment by drnic** [comment]
Hmm I wonder how we support this with the uaac shell wrapper. My shell-fu isn't sure right now. Ideas?

**Comment by william-tran** [comment]
Oh I see what you mean: https://github.com/cloudfoundry-community/traveling-cf-admin/blob/master/packaging/wrappers/uaac.sh#L13

**Comment by william-tran** [comment]
The last comment on this issue explains the need for wrapping $@ in quotes. I'll make a PR.
